# 1. Site Metadata
title: My Awesome Product Shop
description: A collection of cool things I found online.

# 2. The Collection Setup
collections:
  products:
    output: true

# 3. URL Settings
# This is the main domain
url: "https://chrisinacio.github.io"

# This is the subfolder path for your project repository
baseurl: "/atelie-porta-oito"