name: Jekyll Build Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.3.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Upload built site (optional)
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site